// <auto-generated />
using System;
using AudioGuideAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AudioGuideAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422114010_AddOwnerUserIdToFoodStall")]
    partial class AddOwnerUserIdToFoodStall
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("AudioGuideAPI.Models.FoodStall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("MapLink")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("PriceRange")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Radius")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("FoodStalls");
                });

            modelBuilder.Entity("AudioGuideAPI.Models.FoodStallTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodStallId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("FoodStallId", "LanguageId")
                        .IsUnique();

                    b.ToTable("FoodStallTranslations");
                });

            modelBuilder.Entity("AudioGuideAPI.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagIcon")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("IntroText")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCode")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("AudioGuideAPI.Models.PlaybackLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActualDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodStallId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodStallId");

                    b.ToTable("PlaybackLogs");
                });

            modelBuilder.Entity("AudioGuideAPI.Models.QrMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodStallId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CodeValue")
                        .IsUnique();

                    b.HasIndex("FoodStallId");

                    b.ToTable("QrMappings");
                });

            modelBuilder.Entity("AudioGuideAPI.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("AudioGuideAPI.Models.TourItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodStallId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TourId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FoodStallId");

                    b.HasIndex("TourId", "FoodStallId")
                        .IsUnique();

                    b.ToTable("TourItems");
                });

            modelBuilder.Entity("AudioGuideAPI.Models.TourTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TourId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("TourId", "LanguageId")
                        .IsUnique();

                    b.ToTable("TourTranslations");
                });

            modelBuilder.Entity("AudioGuideAPI.Models.FoodStallTranslation", b =>
                {
                    b.HasOne("AudioGuideAPI.Models.FoodStall", "FoodStall")
                        .WithMany("Translations")
                        .HasForeignKey("FoodStallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudioGuideAPI.Models.Language", "Language")
                        .WithMany("FoodStallTranslations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FoodStall");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("AudioGuideAPI.Models.PlaybackLog", b =>
                {
                    b.HasOne("AudioGuideAPI.Models.FoodStall", "FoodStall")
                        .WithMany()
                        .HasForeignKey("FoodStallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodStall");
                });

            modelBuilder.Entity("AudioGuideAPI.Models.QrMapping", b =>
                {
                    b.HasOne("AudioGuideAPI.Models.FoodStall", "FoodStall")
                        .WithMany()
                        .HasForeignKey("FoodStallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodStall");
                });

            modelBuilder.Entity("AudioGuideAPI.Models.TourItem", b =>
                {
                    b.HasOne("AudioGuideAPI.Models.FoodStall", "FoodStall")
                        .WithMany()
                        .HasForeignKey("FoodStallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AudioGuideAPI.Models.Tour", "Tour")
                        .WithMany("TourItems")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodStall");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("AudioGuideAPI.Models.TourTranslation", b =>
                {
                    b.HasOne("AudioGuideAPI.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AudioGuideAPI.Models.Tour", "Tour")
                        .WithMany("Translations")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("AudioGuideAPI.Models.FoodStall", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("AudioGuideAPI.Models.Language", b =>
                {
                    b.Navigation("FoodStallTranslations");
                });

            modelBuilder.Entity("AudioGuideAPI.Models.Tour", b =>
                {
                    b.Navigation("TourItems");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
