// <auto-generated />
using AudioGuideAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AudioGuideAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260327130640_SeedPOIData")]
    partial class SeedPOIData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("AudioGuideAPI.Models.POI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Radius")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("POIs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AudioUrl = "audio/vinhkhanh.mp3",
                            Description = "Khu phố nổi tiếng với nhiều món ăn đêm.",
                            Latitude = 10.755100000000001,
                            Longitude = 106.7038,
                            Name = "Phố ẩm thực Vĩnh Khánh",
                            Radius = 50.0
                        },
                        new
                        {
                            Id = 2,
                            AudioUrl = "audio/oc.mp3",
                            Description = "Điểm dừng chân gợi ý để trải nghiệm món ốc.",
                            Latitude = 10.754799999999999,
                            Longitude = 106.7041,
                            Name = "Quán ốc nổi bật",
                            Radius = 30.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
